const fs = require('fs')
const st = fs.readFileSync('E:/Movie Vault/src/main/lib/store.ts', 'utf8')
console.log('=== store.ts P2-5 area ===')
const i = st.indexOf('migrateInPlace(current)')
console.log(st.slice(i, i + 450))
console.log('has import getDb:', st.includes("from './db'"))
const im = fs.readFileSync('E:/Movie Vault/src/main/lib/images.ts', 'utf8')
console.log('\n=== images.ts generatePreviewSet refs ===')
im.split('\n').forEach((l, n) => { if (l.includes('generatePreviewSet')) console.log(n + 1, l.trim()) })
const app = fs.readFileSync('E:/Movie Vault/src/renderer/src/App.tsx', 'utf8')
console.log('\n=== App.tsx ORDER area ===')
const j = app.indexOf('RES_ORDER')
console.log(app.slice(Math.max(0, j - 300), j + 600))
